name: Push To Docker Hub

on:
    push:
      branches: [ "master" ]


jobs:
  build-test-push:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Install GO
        uses: actions/setup-go@v3
        with:
          go-version: 1.22

      - name: checkout code
        uses: actions/checkout@v3

      - name: Fetch required go modules
        run: go mod download

      - name: Build 
        run: go build -v ./...

      - name: Build Image
        run: docker build -t alhusseinahmed/go-webapp-sample .

      - name: Test Image 
        run: |  
          docker run -d -p 8080:8080 alhusseinahmed/go-webapp-sample
          sleep 5 
          curl http://localhost:8080/api/health  


      - name: calculate version
        id: calculate-version
        uses: bitshifted/git-auto-semver@v1
        with:
          main_branch: master
          create_tag: true
          tag_prefix: 'v'
        
      - name: Use version
        run: |
          echo "Calculated version: ${{ steps.calculate-version.outputs.version-string }}"

      - name: Push Image
        run: |
          docker tag alhusseinahmed/go-webapp-sample alhusseinahmed/go-webapp-sample:${{ steps.calculate-version.outputs.version-string }}
          docker push alhusseinahmed/go-webapp-sample:${{ steps.calculate-version.outputs.version-string }}




